Feature/survey creation screen
Kazuki0320/GolfApp pull request #31
Opened 2023-01-10 14:42 UTC by Kazuki0320

アンケート作成画面完成しました👏
ただ、前の画面に戻った時に、チェックボックスが活性しなかったりするので、細かい部分は後ほど修正。

- [ ] 各情報の入力（画面側）挙動に問題ないか
- [ ] vuexの状態管理（文字列や配列）についてのデータ保持の仕方
- [ ] vuexの情報が表示されているか
- [ ] questionnaires&schedulesが、「メッセージ送信」発火のタイミングで作成されているか
- [ ] firebase側の各DB保存ができているか

他、疑問に思ったところはイシューにでもまとめて置いて〜

2023-01-11 15:09 UTC, ittyi requested changes
では折角なので、対応必須で！※対応は変更だけではなく、意図の説明なども含みます

2023-01-11 15:11 UTC, Kazuki0320 commented on src/main.js
> +Vue.config.productionTip = false
これはマジで記憶ない。変えたのかな？

2023-01-11 15:13 UTC, Kazuki0320 commented on src/Vuex/store.js
> +		pref1: state => state.pref1,
prefecture:pref
都道府県を２つ利用してるのは、候補地を複数選択するため。←ただ、メンバー選ぶように１つの処理にまとめてもいいかも。

2023-01-11 15:20 UTC, Kazuki0320 commented on src/router/index.js
> +    component: NewSurvey
ごめん、消した覚えがない。笑
そして、この前pullしたはずなのに、みたら全部消えてるね。※多分、GitHub使いこなせてないから起きた事象。
このブランチにpullはしてないからかな？いや、でもマイナスになってるから消したことになってるのか。謎。直す。

2023-01-11 15:30 UTC, ittyi commented on src/main.js
> +Vue.config.productionTip = false
たぶん、git pullしたときのコンフリクト解消時とかですかね～

2023-01-11 15:39 UTC, ittyi commented on src/Vuex/store.js
> +		pref1: state => state.pref1,
なるほど～
都道府県１、都道府県２とかだと名前を見ただけで使用され方の想像はつきづらい気がするので、candidatePrefecture（候補都道府県）とかのほうが好きかもしれません

2023-01-12 12:02 UTC, Kazuki0320 commented on src/Vuex/store.js
> +		updateRemark({commit}, newRemark) {
ごめん、これだけちょっと時間かかりそうだったから後回し🙇‍♂️

2023-01-12 13:07 UTC, ittyi commented on src/main.js
> +Vue.config.productionTip = false
まぁこちらは大したことではないので、私の方で直しました。

2023-01-13 02:15 UTC, ittyi commented on src/Vuex/store.js
> +		updateRemark({commit}, newRemark) {
後々にペアプロしませう

2023-01-13 02:17 UTC, ittyi approved these changes
LGTM！
ひとまず、形になっていて、Vuexのキャッチアップから進め完成させたのナイスです〜〜🤗

2023-01-13 02:17 UTC, merged

2023-01-13 02:26 UTC, ittyi commented
memo
「vuexの情報が表示されているか」 - > 確認ボタン押下後にデータが引き継がれて画面に表示されているか