[surveyConfirmed]アンケート作成して「メッセージ送信」したタイミングで、roomsのmessageにquestionnairesIdを追加する処理
Kazuki0320/GolfApp pull request #43
Opened 2023-01-20 06:01 UTC by Kazuki0320

### 内容
- roomsのフィールドにアンケート情報を追加
- questionnairesIdをmessageに追加

- [ ] メッセージ送信を押したタイミングで、roomsの中にフィールド値（作成したuserName,questionnairesId,作成したuserId)
- [ ] メッセージ送信を押したタイミングで、questionnaresIdがmessageの中に作成されるか確認
- [ ] メッセージ送信を押したタイミングで、shcedulesにIDが作成されるか
- [ ] メッセージ送信を押したタイミングで、questionnairesにIDが作成されるか

2023-01-20 07:30 UTC, Kazuki0320 commented
### 追加
270行目のcollection("massage")→messageに直しといて笑

2023-01-20 16:15 UTC, ittyi commented
何も入力せずにとりあえずメッセージを送信したら、エラー吐きました....！
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/62760395/213748796-da404bbc-1b6a-43b9-9495-5b1e2ec1705a.png">

2023-01-20 16:21 UTC, ittyi commented
また、アンケート記入後、確認画面でブラウザを更新するとデータが飛んでいるように見えます。
ちょっとテストユーザーにフレンドがいないので、フレンドがいるアカウントのパスワードをSlackのDMなどで教えてほしいです〜

フレンドがいないからなのかはわかりませんが、以下のようなエラーが出ています。
<img width="489" alt="image" src="https://user-images.githubusercontent.com/62760395/213750146-b6774224-8eb7-4f2e-a911-61f76118d4a8.png">
[これでログイン](https://w1618657437-cir282308.slack.com/archives/D03Q4JG7SJV/p1672813822548209)してみてください〜
- また、このアプリの初期ユーザーはフレンドがいない場合も考えられるのではと思っているのですが、その対処はしなくても大丈夫でしょうか？

2023-01-20 16:41 UTC, ittyi requested changes
コードも確認いたしました！
ご確認をよろしくお願いいたします。

2023-01-20 16:41 UTC, ittyi commented on src/views/ChatBoard.vue
> +			console.log("questionnairesData", questionnaires)
そろそろ、いらないコンソールやコメントは削除する癖をつけましょう！
テスト用に使う場合などは、コメントで明記いただけますと幸いです。ただ、それもPRのコメントでいいかな〜とも。

いらないコメントアウトも同様です！

2023-01-20 16:41 UTC, ittyi commented on src/views/ChatBoard.vue
>  			const snapshot = await roomRef.collection("messages").orderBy("createdAt", "asc").get()
こちら変更には対応しました！
次からはファイルの場所も教えていただけますと嬉しいです〜

2023-01-20 16:41 UTC, ittyi commented on src/views/SurveyConfirmed.vue
> +		userData: '',
そういえばになりますが、変数自体がデータを格納するものなので、基本的に「なんとかデータ」のような名付けは避けた方がいいかもです〜

2023-01-20 16:41 UTC, ittyi commented on src/views/roomList.vue
> +			<div></div>
これは必要な空のdivタグですか？

2023-01-21 01:14 UTC, ittyi commented on src/views/ChatBoard.vue
> +			console.log("questionnairesData", questionnaires)
と思いきや、このファイル見なくていいのか🤔

2023-01-21 01:15 UTC, ittyi commented on src/views/roomList.vue
> +			<div></div>
このファイルもいいのか🤔
ただ、この削除は多少気になるかも…

2023-01-21 01:52 UTC, Kazuki0320 commented on src/views/roomList.vue
> +			<div></div>
これは後々グループ名とかを表示するのに使うかもだけど、一旦いらないかも。

2023-01-21 01:57 UTC, Kazuki0320 commented on src/views/SurveyConfirmed.vue
> +		userData: '',
issue作成完了

2023-01-21 03:09 UTC, merged